INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Catherine','Ardagh','Fianna Fáil','Dublin South Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Heather','Humphries','Fine Gael','Cavan-Monaghan');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Richard','Bruton','Fine Gael','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Charlie','McConalogue','Fianna Fáil','Donegal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mary','Mitchell-O''Connor','Fine Gael','Dún Laoghaire');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Eric','Byrne','Labour Party','Dublin South Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Seán','Conlan','Fine Gael','Cavan-Monaghan');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Pat','Gallagher','Fianna Fáil','Donegal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Joe','O''Reilly','Fine Gael','Cavan-Monaghan');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Cahterine','Byrne','Fine Gael','Dublin South Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Caoimhghín','Ó Caoláin','Sinn Féin','Cavan-Monaghan');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Joan','Collins','Independent','Dublin South Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Eamon','Ryan','Green Party','Dublin Bay South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paschal','Donohoe','Fine Gael','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tommy','Broughan','Independent','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Joe','McHugh','Fine Gael','Donegal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Kathryn','Reilly','Sinn Féin','Cavan-Monaghan');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Maria','Bailey','Fine Gael','Dún Laoghaire');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Marie','Devine','Sinn Féin','Dublin South Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Terence','Flanagan','Renua','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Brendan','Smith','Fianna Fáil','Cavan-Monaghan');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Pearse','Doherty','Sinn Féin','Donegal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sean','Haughey','Fianna Fáil','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Cormac','Devlin','Fianna Fáil','Dún Laoghaire');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mary','Fitzpatrick','Fianna Fáil','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Niamh','Smyth','Fianna Fáil','Cavan-Monaghan');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Alex','White','Labour Party','Dublin Bay South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paul','Hand','Independent','Dublin South Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Padraig','MacLochlainn','Sinn Féin','Donegal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Aengus','Ó Snodaigh','Sinn Féin','Dublin South Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mary','Smyth','Renua','Cavan-Monaghan');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Joe','Costello','Labour Party','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mary','Hanafin','Fianna Fáil','Dún Laoghaire');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jimmy','Deenihan','Fine Gael','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Colm','Brophy','Fine Gael','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Brid','Smith','People Before Profit Alliance','Dublin South Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Deirdre','Heney','Fianna Fáil','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Carrie','Smyth','Labour Party','Dún Laoghaire');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Oisín','Ó hAlmhain','Green Party','Dublin South Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Brendan','Griffin','Fine Gael','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Thomas','Pringle','Independent','Donegal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Fergus','O''Dowd','Fine Gael','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Anne-Marie','Dermody','Fine Gael','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Richard','Murray','Independent','Dublin South Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Shane','O''Brien','Sinn Féin','Dún Laoghaire');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mary Lou','McDonald','Sinn Féin','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Peter','Casey','Independent','Donegal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Peter','Fitzpatrick','Fine Gael','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Grace','O''Donnell','Fine Gael','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Cian','O''Callaghan','Social Democrats','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Declan','Breathnach','Fianna Fáil','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Niamh','Kennedy','Independent','Donegal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Alan','Shatter','Fine Gael','Dublin Rathdown');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Gerry','Adams','Sinn Féin','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Norma','Moriarty','Fianna Fáil','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Richard','Boyd-Barrett','People Before Profit Alliance','Dún Laoghaire');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Karen','Warren','Fine Gael','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','O''Donnell','Independent','Donegal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Gary','Gannon','Social Democrats','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Josepha','Madigan','Fine Gael','Dublin Rathdown');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Brassil','Fianna Fáil','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Imelda','Munster','Sinn Féin','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Aodhan','O'' Riordan','Labour Party','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Healy Rae','Independent','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Frank','Cronin','Renua','Dún Laoghaire');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Martin','Ferris','Sinn Féin','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Arthur','Spring','Labour Party','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Lahart','Fianna Fáil','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ãilis','Ryan','The Workers'' Party','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ossian','Smyth','Green Party','Dún Laoghaire');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Enda','Kenny','Fine Gael','Mayo');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Lyons','People Before Profit Alliance','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Brian','Finucane','People Before Profit Alliance','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mary','White','Fianna Fáil','Dublin Rathdown');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Carol','Hunt','Independent','Dún Laoghaire');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Pamela','Kearns','Labour Party','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Alex','White','Labour Party','Dublin Rathdown');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Ring','Fine Gael','Mayo');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Stephanie','Regan','Fine Gael','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Diana','O''Dwyer','Independent','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tom','Fleming','Independent','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michelle','Mulherin','Fine Gael','Mayo');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Averil','Power','Independent','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mick','Duff','Labour Party','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','O''Gorman','Independent','Kerry');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Lisa','Chambers','Fianna Fáil','Mayo');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sorcha','Nic Cormaic','Sinn Féin','Dublin Rathdown');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Naoise','O'' Muiri','Fine Gael','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Dara','Calleary','Fianna Fáil','Mayo');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sarah','Holland','Sinn Féin','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Catherine','Martin','Green Party','Dublin Rathdown');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Noonan','Fine Gael','Limerick City');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Mac Donncha','Sinn Féin','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Rose','Conway-Walsh','Sinn Féin','Mayo');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sean','Crowe','Sinn Féin','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Denise','Mitchell','Sinn Féin','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Christy','Burke','Independent','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tom','Moran','People Before Profit Alliance','Mayo');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paul','Connaughton','Fine Gael','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ciaran','Cannon','Fine Gael','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Farrington','Renua','Mayo');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Willie','O''Dea','Fianna Fáil','Limerick City');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Finian','McGrath','Independent','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Cieran','Perry','Independent','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Shane','Ross','Independent','Dublin Rathdown');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Anne','Rabbitte','Fianna Fáil','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Maurice','Quinlivan','Sinn Féin','Limerick City');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jerry','Buttimer','Fine Gael','Cork South-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Gerry','O''Boyle','Independent','Mayo');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jan','O''Sullivan','Labour Party','Limerick City');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('David','Healy','Green Party','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Maureen','O''Sullivan','Independent','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paul','Murphy','Independent','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Marcella','Corcoran-Kennedy','Fine Gael','Offaly');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Simon','Coveney','Fine Gael','Cork South-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Colm','Keaveney','Fianna Fáil','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Peter','Matthews','Independent','Dublin Rathdown');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Kieran','O''Donnell','Fine Gael','Limerick City');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jimmy','Guerin','Independent','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Nicola','Curry','Independent','Dublin Rathdown');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Lorraine','Higgins','Labour Party','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Micheal','Martin','Fianna Fáil','Cork South-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Cian','Prendiville','Independent','Limerick City');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sandra','Fay','Independent','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Damien','English','Fine Gael','Meath West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Annemarie','Roche','Sinn Féin','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','McGrath','Fianna Fáil','Cork South-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sarah Jane','Hennelly','Social Democrats','Limerick City');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Andrew','Kelly','Independent','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Desmond','J Hayes','Renua','Limerick City');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Donna','Cooney','Green Party','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sean','Canney','Independent','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Barry','Cowen','Fianna Fáil','Offaly');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Fahy','Independent','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paul','Clarke','Independent','Dublin Bay North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Deasy','Fine Gael','Waterford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ciaran','Lynch','Labour Party','Cork South-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Shane','Cassells','Fianna Fáil','Meath West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Eddie','Fitzpatrick','Fianna Fáil','Offaly');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paudie','Coffey','Fine Gael','Dublin Rathdown');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ronan','McMahon','Renua','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Carol','Nolan','Sinn Féin','Offaly');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Noel','Rock','Fine Gael','Dublin North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Leahy','Renua','Offaly');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Katherine','Zappone','Independent','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mary','Butler','Fianna Fáil','Waterford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paul','McAuliffe','Fianna Fáil','Dublin North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Thomas','Gould','Sinn Féin','Cork North-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ken','Smollen','Irish Democratic Party','Offaly');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Hildegarde','Naughten','Fine Gael','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Deirdre','O''Donovan','Independent','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ciara','Conway','Labour Party','Waterford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tracy','McElhinney','Labour Party','Meath West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Foley','Independent','Offaly');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mick','Barry','Independent','Cork North-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sean','Kyne','Fine Gael','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Peadar','TÃ³ibín','Sinn Féin','Meath West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('David','Cullinane','Sinn Féin','Waterford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Kathleen','Lynch','Labour Party','Cork North-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Brian','Walsh','Fine Gael','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Eamonn','Maloney','Independent','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Seamus','McMenamin','Green Party','Meath West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Johnathan','O''Brien','Sinn Féin','Cork North-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','O''Mahony','Fine Gael','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Eamon','O''Cuiv','Fianna Fáil','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mailo','Power','Renua','Waterford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Peter','Fitzpatrick','Independent','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mary','Moran','Labour Party','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Lyons','Labour Party','Dublin North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Billy','Kelleher','Fianna Fáil','Cork North-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Gerald','Nash','Labour Party','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mary','Hoade','Fianna Fáil','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Una','Dunphy','People Before Profit Alliance','Waterford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Connolly','Fianna Fáil','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Dara','Murphy','Fine Gael','Cork North-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Derek','Nolan','Labour Party','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Trevor','O''Clochartaigh','Sinn Féin','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tommy','Holohan','Independent','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','O''Dowd','Renua','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Halligan','Independent','Waterford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Declan','Burke','Independent','Dublin South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Niall','Ó'' Tuathail','Social Democrats','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Oliver','Moran','Green Party','Cork North-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Seamus','Sheridan','Green Party','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tommy','Roddy','Independent','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Seona','O''Fegan','Independent','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ted','Tynan','The Workers'' Party','Cork North-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('James','Charity','Independent','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Fidelma','Healy Eames','Independent','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Noel','Grealish','Independent','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Catherine','Connolly','Independent','Galway West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Cormac','Mckay','Independent','Dublin Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Eoghan','Murphy','Fine Gael','Dublin Bay South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Kate','O''Connell','Fine Gael','Dublin Bay South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jim','O''Callaghan','Fianna Fáil','Dublin Bay South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Kevin','Humphreys','Labour Party','Dublin Bay South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Chris','Andrews','Sinn Féin','Dublin Bay South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Annette','Mooney','People Before Profit Alliance','Dublin Bay South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Gareth','Weldon','People Before Profit Alliance','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mark','Dearey','Green Party','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Anthony','Connor','Direct Democracy Ireland','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Pat','Deering','Fine Gael','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Pat','Greene','Direct Democracy Ireland','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John Paul','Phelan','Fine Gael','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jeff','Rudd','Independent','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('David','Fitzgerald','Fine Gael','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Kevin','Callan','Independent','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','McGuinness','Fianna Fáil','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Maeve','Yore','Independent','Louth');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Bobby','Aylward','Fianna Fáil','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jennifer','Murnane O''Connor','Fianna Fáil','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ann','Phelan','Labour Party','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Kathleen','Funchion','Sinn Féin','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Malcolm','Noonan','Green Party','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Patrick','McKee','Renua','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Noel','Walsh','Independent','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Andrew','Doyle','Fine Gael','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Simon','Harris','Fine Gael','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jennifer','Cuffe','Fianna Fáil','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Pat','Casey','Fianna Fáil','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Anne','Ferris','Labour Party','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Brady','Sinn Féin','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Anna','Doyle','Independent','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sharon','Briggs','People Before Profit Alliance','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Billly','Timmins','Renua','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Maura','Hopkins','Fine Gael','Roscommon-Galway');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Anne','Farrell','Renua','Roscommon-Galway');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Eddie','Conroy','people Before Profit Alliance','Roscommon-Galway');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paul','Kehoe','Fine Gael','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Brendan','Howlin','Labour Party','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','D''Arcy','Fine Gael','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Malcolm','Byrne','Fianna Fáil','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('James','Browne','Fianna Fáil','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mick','Wallace','Independent','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Stephen','Donnelly','Social Democrats','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Steven','Matthews','Green Party','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Joe','Behan','Independent','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Pat','Kavanagh','Independent','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Charlie','Keddy','Independent','Wicklow');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sean','Canney','Independent','Roscommon-Galway');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Colm','Keaveney','Fianna Fáil','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paul','Connaughton','Fine Gael','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ciaran','Cannon','Fine Gael','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Lorraine','Higgins','Labour Party','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Anne Marie','Roche','Sinn Féin','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Anne','Rabbitte','Fianna Fáil','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Fahy','Independent','Galway East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Kelly','Labour Party','Roscommon-Galway');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Claire','Kerrane','Sinn Féin','Roscommon-Galway');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Robert','Troy','Fianna Fáil','Longford-Westmeath');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paul','Hogan','Sinn Féin','Longford-Westmeath');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Gabrielle','McFadden','Fine Gael','Longford-Westmeath');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('James','Bannon','Fine Gael','Longford-Westmeath');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Kevin ''Boxer''','Moran','Independent','Longford-Westmeath');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Peter','Burke','Fine Gael','Longford-Westmeath');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Gerry','Warnock','Social Democrats','Longford-Westmeath');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Barbara','Smyth','Independent','Longford-Westmeath');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Rachel','Grimes','Renua','Longford-Westmeath');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jimmy','Duffy','People Before Profit Alliance','Longford-Westmeath');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Pat','Breen','Fine Gael','Clare');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Joe','Carey','Fine Gael','Clare');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Johnny','Mythen','Sinn Féin','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Deirdre','Wadding','People Before Profit Alliance','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Leonard','Kelly','Social Democrats','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('David','Lloyd','Direct Democracy Ireland','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Caroline','Foxe','Independent','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Emmet','Moloney','Independent','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Breda','Cahill','Independent','Wexford');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Anthony','Lawlor','Fine Gael','Kildare North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Bernard','Durkan','Fine Gael','Kildare North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('James','Lawless','Fianna Fáil','Kildare North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Frank','O''Rourke','Fianna Fáil','Kildare North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Emmett','Stagg','Labour Party','Kildare North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('RÃ©ada','Cronin','Sinn Féin','Kildare North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Catherine','Murphy','Social Democrats','Kildare North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ashling','Merriman','People Before Profit Alliance','Kildare North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Brendan','Young','Independent','Kildare North');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('James','Reilly','Fine Gael','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Alan','Farrell','Fine Gael','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Darragh','O''Brien','Fianna Fáil','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Lorraine','Clifford Lee','Fianna Fáil','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Brendan','Ryan','Labour Party','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Louise','O''Reilly','Sinn Féin','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Joe','O''Brien','Green Party','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Barry','Martin','People Before Profit Alliance','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Terry','Kelleher','Independent','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Clare','Daly','Independent','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Roslyn','Fuller','Independent','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tony','Murphy','Independent','Dublin Fingal');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Noel','Coonan','Fine Gael','Tipperary');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tom','Hayes','Fine Gael','Tipperary');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Marie','Murphy','Fine Gael','Tipperary');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jackie','Cahill','Fianna Fáil','Tipperary');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Siobhan','Ambrose','Fianna Fáil','Tipperary');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Smith','Fianna Fáil','Tipperary');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Alan','Kelly','Labour Party','Tipperary');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Seamus','Morris','Sinn Féin','Tipperary');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Seamus','Healy','Independent','Tipperary');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Lowry','Independent','Tipperary');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Gerry','Reynolds','Fine Gael','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tony','McLoughlin','Fine Gael','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Eamon','Scanlon','Fianna Fáil','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Marc','MacSharry','Fianna Fáil','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Susan','O''Keefe','Labour Party','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Martin','Kenny','Sinn Féin','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Chris','MacManus','Sinn Féin','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Finbarr','Filan','Renua','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Nigel','Gallagher','People Before Profit Alliance','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Leslie','O''Hora','Green Party','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Marie','Casserly','Independent','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Declan','Bree','Independent','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Bernard','Sweeney','Independent','Sligo-Leitrim');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Patrick','O''Donovan','Fine Gael','Limerick County');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tom','Neville','Fine Gael','Limerick County');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Niall','Collins','Fianna Fáil','Limerick County');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Seamus','Browne','Sinn Féin','Limerick County');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('James','Heffernan','Social Democrats','Limerick County');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Emmett','O''Brien','Independent','Limerick County');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Patricia','Ryan','Sinn Féin','Kildare South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sean O','O''Fearghail','Fianna Fáil','Kildare South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Fiona','McLoughlin','Fianna Fáil','Kildare South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Regina','Doherty','Fine Gael','Meath East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Fiona','McLoughlin-Healy','Fine Gael','Kildare South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Martin','Heydon','Fine Gael','Kildare South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Helen','McEntee','Fine Gael','Meath East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mark','Wall','Labour Party','Kildare South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Thomas','Byrne','Fianna Fáil','Meath East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Dominic','Hannigan','Labour Party','Meath East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Darren','O''Rourke','Sinn Féin','Meath East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Seán','Ó Buachalla','Green Party','Meath East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('SÃ©amus','McDonagh','The Workers'' Party','Meath East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Aisling','O''Neill','Social Democrats','Meath East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ben','Gilroy','Direct Democracy Ireland','Meath East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sharon','Keogan','Independent','Meath East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Lorraine','Hayde','Independent','Kildare South');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Charlie','Flanagan','Fine Gael','Laois');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Thomasina','Connell','Fine Gael','Laois');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Catherine','Noone','Fine Gael','Dublin West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Whelan','Labour Party','Laois');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Leo','Varadkar','Fine Gael','Dublin West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jack','Chambers','Fianna Fáil','Dublin West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sean','Fleming','Fianna Fáil','Laois');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Joan','Burton','Labour Party','Dublin West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paul','Donnelly','Sinn Féin','Dublin West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ruth','Coppinger','Socialist Party','Dublin West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Brian','Stanley','Sinn Féin','Laois');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sinead','Moore','Green Party','Laois');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Roderic','O''Gorman','Green Party','Dublin West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Lorna','Nolan','Independent','Dublin West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('David','McGuinness','Independent','Dublin West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('TJ','Clare','Independent','Dublin West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Aine','Collins','Fine Gael','Cork North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Creed','Fine Gael','Cork North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Moynihan','Fianna Fáil','Cork North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Aindrias','Moynihan','Fianna Fáil','Cork North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Nigel','Dennehy','Sinn Féin','Cork North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Cork','Manning','Green Party','Cork North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John Paul','O''Shea','Independent','Cork North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Steven','O''Riordabn','Independent','Cork North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Diarmuid','O''Flynn','Independent','Cork North-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Frances','Fitzgerald','Fine Gael','Dublin Mid-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Derek','Keating','Fine Gael','Dublin Mid-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('John','Curran','Fianna Fáil','Dublin Mid-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Joanna','Tuffy','Labour Party','Dublin Mid-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Eoin','Ó Broin','Sinn Féin','Dublin Mid-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Gino','Kenny','People Before Profit Alliance','Dublin Mid-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Anne-Marie','McNally','Social Democrats','Dublin Mid-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Francis','Timmons','Independent','Dublin Mid-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Donnchadh','Ó Laoghaire','Sinn Féin','Cork North-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Lorna','Bogue','Green Party','Cork South-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jim','O''Connell','People Before Profit Alliance','Cork South-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Rose','Leadbetter','Independent','Cork South-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Mick','Finn','Independent','Cork South-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Diarmaid','Ó Cadhla','Independent','Cork South-Central');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Richard','Cahill','Independent','Clare');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Adrienne','Wallace','People Before Profit Alliance','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Conor','Mac Liam','Independent','Carlow-Kilkenny');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Timmy','Dooley','Fianna Fáil','Clare');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','McDonagh','Fianna Fáil','Clare');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Clare','Colleran Molloy','Fianna Fáil','Clare');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ann','Norton','Independent','Clare');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','McNamara','Labour Party','Clare');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Noeleen','Moran','Sinn Féin','Clare');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Kevin','O''Keefe','Fianna Fáil','Cork East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Tom','Barry','Fianna Fáil','Cork East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('David','Stanton','Fine Gael','Cork East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Sean','Sherlock','Labour Party','Cork East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Pat','Buckley','Sinn Féin','Cork East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ciara','Leonardi Roche','Independent','Cork East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Paul','Bradford','Renua','Cork East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ken','Curtain','Social Democrats','Cork East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Ken','Curtain','Social Democrats','Cork East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Claire','Cullinane','Independent','Cork East');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Noel','Harrington','Fine Gael','Cork South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Jim','Daly','Fine Gael','Cork South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Margaret','Murphy O''Mahony','Fianna Fáil','Cork South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','McCarthy','Labour Party','Cork South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Rachel','McCarthy','Sinn Féin','Cork South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Alan','Coleman','Independent','Cork South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Michael','Collins','Independent','Cork South-West');
INSERT INTO candidates(First_name,Second_name,Party,Constituency) VALUES ('Andrew','Keegan','People Before Profit Alliance','Dublin North-West');
